# Generated by Django 6.0 on 2025-12-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#667eea', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(default='bi-tag', max_length=50),
        ),
    ]
