# Generated by Django 6.0 on 2025-12-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_tag_color_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
